### PR TITLE
Palindrome Checker💙💙

### PR DESCRIPTION
**Pull request by WALWALASAFI**
A palindrome is a sequence of characters that remains unchanged when read backward. For example, "radar" and "madam" are palindromes because they read the same from left to right and right to left. The input to a palindrome checker is usually a string of characters. This string can include letters, digits, and other symbols.
Certainly! A palindrome is a sequence of characters that reads the same backward as forward. For example, "radar" and "madam" are palindromes because if you reverse the characters, you get the same sequence.
Certainly! A palindrome is a sequence of characters that reads the same backward as forward. For example, "radar" and "madam" are palindromes because if you reverse the characters, you get the same sequence.🔹

When creating a palindrome checker in JavaScript, there are several steps involved:

Input Handling: Retrieve the input string from the user. This can be done using an input field (<input> element) in HTML.

Normalization: Convert the input string to a consistent format to ignore case sensitivity and non-alphanumeric characters. Typically, this involves:🔹

### CODE REVIEW

**Comment by WALWALASAFI** [comment]
check the code

**Comment by WALWALASAFI** [comment]
@zohalmirkhel 
darling check the project
and give me feedback as soon as possible.
thanks in advance!~~~

**Comment by ZohalMirkhel** [comment]
Dear @WALWALASAFI,

There are a few errors in your project. 

- First off, you haven't added the needed linter files.
- Your HTML code isn't clean; try adding double spaces.
- Make sure to add the linter files from the html-css-js folder, not the html-css folder.
- In some places, your CSS code doesn't meet the linters' requirements. Try editing those parts.
- Your project design doesn't match the provided design requirements.
- Also, your commit messages need to be more detailed.

Thank you so much, keep up the great work, we will get there together with the help of each other!

**Comment by WALWALASAFI** [comment]
@ZohalMirkhel,
hello Darling, i hope ur fine . 
as you mentioned some changes. 
i have corrected and done the changes.
first i gave more description about Palindrome Checker
second, I corrected the linters error also, it checks completely correct.
third, it passed the free code camp task requirement.
finally, give some changes in CSS. 

I hope that be reliable and acceptable.

thanks in advance.

**Review by ahzamir — CHANGES_REQUESTED** [review]
image

@WALWALASAFI 

You have done a great job by implementing lots of requirements but still your code misses some of the requirements bellow:
- Failed: When you click on the #check-btn element without entering a value into the #text-input element, an alert should appear with the text "Please input a value".

**Comment by WALWALASAFI** [comment]
HI dear   sir @ahzamir ,
i hope ur fine and doing great 
i have given the alert ,
however, it brought space problem in js file. 
i am not sure it is the net problem , i fixed and pushed it to github, same over it showed the error. for this reason my commit got more.
 hope it will be approved.
thanks in advance sir

**Review by ahzamir — APPROVED** [review]
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- [OPTIONAL] - Your input height size is a little bit more, and not looks better in different vies please make it a little bit smaller and then merge your branch.

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
